# 端口号
server:
  port: 12265
spring:  
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://127.0.0.1:3306/primeton_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
          username: root
          password: 778J334x08_M
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
          


## 该配置节点为独立的节点，如果放在spring的节点下，导致配置无法被识别
mybatis:
  # 加载全局的配置文件
  config-location: classpath:mybatis/sqlMapConfig.xml
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:mybatis/mapper/*.xml  

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#log4j2记录日志   
logging:
  config: classpath:log4j2.xml
    
